"""Narzędzia CLI do zrzutu i wczytania konfiguracji z plików CSV.

Krok 15 refactoru B01 (decyzja D5): kod obsługujący `--task store` / `--task load`
wyszedł z klasy `Game` do funkcji operujących na `conf`. Moduł jest DESKTOP-ONLY
(importuje `config_pydantic`) i wolno go importować wyłącznie leniwie, w gałęzi
zadania CLI - kontrakt K5 zabrania wciągania pydantic do builda web.
"""
from typing import Any

from rich import print

from config_model.config_pydantic import save_config
from settings import CONFIG_DIR, CONF_ENTITIES_TO_STORE


def store_config_to_csv(conf: Any, entities: list[str]) -> None:
    """Zrzuć wybrane encje konfiguracji do plików CSV (jeden plik na encję)."""
    if "all" in entities:
        entities = list(CONF_ENTITIES_TO_STORE.keys())

    for entity_name in CONF_ENTITIES_TO_STORE:
        if entity_name in entities:
            file_name = CONFIG_DIR / f"{entity_name}.csv"
            print(f"[yellow]Storing[/] '{entity_name}' [yellow]to[/] '{file_name}'")
            entity_fields = CONF_ENTITIES_TO_STORE[entity_name]
            with open(file_name, "w") as f:
                f.write(";".join(["key"] + entity_fields))
                f.write("\n")
                objects = getattr(conf, entity_name)
                for key, object in objects.items():
                    values = [str(key)] + [str(getattr(object, field)) for field in entity_fields]
                    f.write(";".join(values))
                    f.write("\n")


###############################################################################################################
def load_config_from_csv(conf: Any, entities: list[str]) -> None:
    """Wczytaj wartości liczbowe z CSV do konfiguracji i zapisz `autogenerated_config.json`."""
    if "all" in entities:
        entities = list(CONF_ENTITIES_TO_STORE.keys())

    for entity_name in CONF_ENTITIES_TO_STORE:
        if entity_name in entities:
            file_name = CONFIG_DIR / f"{entity_name}.csv"
            print(f"[yellow]Loading[/] '{entity_name}' [yellow]from[/] '{file_name}'")
            # entity_fields = CONF_ENTITIES_TO_STORE[entity_name]
            with open(file_name, "r") as f:
                data = f.readlines()
            objects = getattr(conf, entity_name)
            # skip "\n" at the end
            fields = data[0][:-1].split(";")
            for line in data[1:]:
                # skip "\n" at the end
                values = line[:-1].split(";")
                key = values[0]
                if entity_name == "maze_configs":
                    key = int(key)  # type: ignore[assignment]

                if key in objects:
                    object = objects[key]
                    for i, value in enumerate(values[1:]):
                        # +1 to skip 'key' field
                        field: Any = getattr(object, fields[i + 1])
                        if type(field) is int:
                            setattr(object, fields[i + 1], int(value))
                        elif type(field) is float:
                            setattr(object, fields[i + 1], float(value))

    save_config(conf, CONFIG_DIR / "autogenerated_config.json")
